from os import system,path,listdir,getcwd,mkdir
from json import loads as JsonLoad
from json import dump as DoJson
from colorama import *
from tomllib import loads as TomlLoad
import keyboard

parent_dir = path.dirname(path.realpath(__file__))

OBJT_DIR = "directory"
OBJT_FILE = "file"
STRUCTURE = "structure"

def GetType(Type: str) -> str|int:
    if Type[0] != "#":
        return -1
    match Type[1:]:
        case "dir":
            return OBJT_DIR
        case "file":
            return OBJT_FILE
        case "struct":
            return STRUCTURE
        case _:
            return -1

def MakeFile(path: str) -> None:
    with open(path,"w") as f:
        f.close()



def ListToString(_list: list[str]) -> str:
    string = ""
    for i in _list:
        string += i + " "
    return string

def getc():
    try:
        return keyboard.read_key()
    except KeyboardInterrupt:
        return None

def RunCommand(command,args):
    system(f"{command} {ListToString(args)}")

with open(path.join(parent_dir,"UseConfig")) as d:
    ConfigPath = TomlLoad(d.read())["active"]

def struct(name: str,entry: str) -> None:
    mkdir("lib")
    mkdir("res")
    mkdir("src")
    mkdir("docs")
    MakeFile("Readme")
    with open(".spin","w") as f:
        with open(ConfigPath) as f:
            config = JsonLoad(f.read())
        DoJson(config,f)
        f.close()
    with open("Readme","w") as about:
        about.write(f"\n\nproject: {name}\nentry: {entry}\n\ngenerated by Spiner. copyright 2024 EliaOndacs")
    MakeFile("License".upper())

if ".spin" in listdir(getcwd()):
    IsSpin = True
    Spin = path.join(getcwd(),".spin")
else:
    IsSpin = False
    Spin = ConfigPath
if IsSpin == True:
    with open(".spin") as f:
        config = JsonLoad(f.read())
else:
    with open(ConfigPath) as f:
        config = JsonLoad(f.read())


